/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"
#include "JSAddEventListenerOptions.h"

#include "JSAbortSignal.h"
#include "JSDOMConvertBoolean.h"
#include "JSDOMConvertInterface.h"
#include "ZigGlobalObject.h"
#include <JavaScriptCore/JSCInlines.h>
#include <JavaScriptCore/PrivateName.h>
#include <JavaScriptCore/Symbol.h>

namespace WebCore {
using namespace JSC;

// Unique SymbolImpl shared by jsResistStopPropagationSymbol() and addEventListener
// options parsing. Not forgeable via string keys, Symbol(), or Symbol.for().
// https://github.com/nodejs/node/blob/main/lib/internal/event_target.js
static PrivateName& resistStopPropagationPrivateName()
{
    static PrivateName name(PrivateName::Description, String("kResistStopPropagation"_s));
    return name;
}

JSC::JSValue jsResistStopPropagationSymbol(Zig::GlobalObject* globalObject)
{
    return Symbol::create(globalObject->vm(), resistStopPropagationPrivateName().uid());
}

template<> AddEventListenerOptions convertDictionary<AddEventListenerOptions>(JSGlobalObject& lexicalGlobalObject, JSValue value)
{
    auto& vm = JSC::getVM(&lexicalGlobalObject);
    auto throwScope = DECLARE_THROW_SCOPE(vm);
    bool isNullOrUndefined = value.isUndefinedOrNull();
    auto* object = isNullOrUndefined ? nullptr : value.getObject();
    if (!isNullOrUndefined && !object) [[unlikely]] {
        throwTypeError(&lexicalGlobalObject, throwScope);
        return {};
    }
    AddEventListenerOptions result;
    JSValue captureValue;
    if (isNullOrUndefined)
        captureValue = jsUndefined();
    else {
        captureValue = object->get(&lexicalGlobalObject, Identifier::fromString(vm, "capture"_s));
        RETURN_IF_EXCEPTION(throwScope, {});
    }
    if (!captureValue.isUndefined()) {
        result.capture = convert<IDLBoolean>(lexicalGlobalObject, captureValue);
        RETURN_IF_EXCEPTION(throwScope, {});
    } else
        result.capture = false;
    JSValue onceValue;
    if (isNullOrUndefined)
        onceValue = jsUndefined();
    else {
        onceValue = object->get(&lexicalGlobalObject, Identifier::fromString(vm, "once"_s));
        RETURN_IF_EXCEPTION(throwScope, {});
    }
    if (!onceValue.isUndefined()) {
        result.once = convert<IDLBoolean>(lexicalGlobalObject, onceValue);
        RETURN_IF_EXCEPTION(throwScope, {});
    } else
        result.once = false;
    JSValue passiveValue;
    if (isNullOrUndefined)
        passiveValue = jsUndefined();
    else {
        passiveValue = object->get(&lexicalGlobalObject, Identifier::fromString(vm, "passive"_s));
        RETURN_IF_EXCEPTION(throwScope, {});
    }
    if (!passiveValue.isUndefined()) {
        result.passive = convert<IDLBoolean>(lexicalGlobalObject, passiveValue);
        RETURN_IF_EXCEPTION(throwScope, {});
    }
    JSValue signalValue;
    if (isNullOrUndefined)
        signalValue = jsUndefined();
    else {
        signalValue = object->get(&lexicalGlobalObject, Identifier::fromString(vm, "signal"_s));
        RETURN_IF_EXCEPTION(throwScope, {});
    }
    if (!signalValue.isUndefined()) {
        result.signal = convert<IDLInterface<AbortSignal>>(lexicalGlobalObject, signalValue);
        RETURN_IF_EXCEPTION(throwScope, {});
    }
    // Own-property lookup only: prototype pollution / string keys / userland
    // Symbol() / Symbol.for() must not opt into non-suppressible dispatch.
    if (object) {
        if (JSValue resistValue = object->getDirect(vm, Identifier::fromUid(resistStopPropagationPrivateName()))) {
            result.resistStopPropagation = resistValue.toBoolean(&lexicalGlobalObject);
            RETURN_IF_EXCEPTION(throwScope, {});
        }
    }
    return result;
}

} // namespace WebCore
